[package]
name = "bevy_ecs_ldtk"
description = "An ECS-friendly ldtk plugin for bevy."
version = "0.2.0"
edition = "2021"
authors = ["Trevor Lovell <trevorlovelldesign@gmail.com>"]
repository = "https://github.com/Trouv/bevy_ecs_ldtk"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "ldtk", "game", "gamedev", "map-editor"]
categories = ["game-development"]
exclude = ["assets/*", "repo/*", "scripts/*"]

[dependencies]
bevy_ecs_ldtk_macros = { version = "0.2", optional = true, path = "macros" }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", rev = "e4270e1c92ff56dd343eeb75504a1dbc5577ce44" }
bevy = { version = "0.6", default-features = false }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"
hex = "0.4"

[dev-dependencies]
bevy = "0.6"
heron = { version = "1.2", features = ["2d"] }
rand = "0.8"

[features]
default = ["derive"]
derive = ["bevy_ecs_ldtk_macros"]
atlas = ["bevy_ecs_tilemap/atlas"]

[[example]]
name = "platformer"
path = "examples/platformer/main.rs"
